const STATS_DATA = {
  "作词": [
    {"name": "冉语优", "count": 11},
    {"name": "司隶示皇-玄天", "count": 10},
    {"name": "慕清明", "count": 5},
    {"name": "择荇", "count": 5},
    {"name": "骆栖淮", "count": 5},
    {"name": "冥凰", "count": 4},
    {"name": "七闷儿", "count": 2},
    {"name": "邪叫教主", "count": 2},
    {"name": "Finale", "count": 1},
    {"name": "丕休哉", "count": 1},
    {"name": "予词", "count": 1},
    {"name": "十灯", "count": 1},
    {"name": "墨大筝", "count": 1},
    {"name": "怀袖", "count": 1},
    {"name": "惊竹娇", "count": 1},
    {"name": "无比", "count": 1},
    {"name": "狐离", "count": 1},
    {"name": "狐離肯定行", "count": 1},
    {"name": "赵素冰", "count": 1},
    {"name": "陆伯让", "count": 1}
  ],
  "作曲": [
    {"name": "陈亦洺", "count": 12},
    {"name": "KBShinya/塔库/禹歌", "count": 10},
    {"name": "酷丘", "count": 6},
    {"name": "litterzy", "count": 3},
    {"name": "潮汐-tide", "count": 3},
    {"name": "PoKeR", "count": 2},
    {"name": "tide-潮汐", "count": 2},
    {"name": "周果亦", "count": 2},
    {"name": "崔博源", "count": 2},
    {"name": "灰原穷", "count": 2},
    {"name": "Ice-Paper", "count": 1},
    {"name": "Mzf小慕", "count": 1},
    {"name": "PokeR", "count": 1},
    {"name": "刘兆伦", "count": 1},
    {"name": "向往", "count": 1},
    {"name": "小可", "count": 1},
    {"name": "悠悠酱", "count": 1},
    {"name": "林华瑞", "count": 1},
    {"name": "殇小谨", "count": 1},
    {"name": "水沐", "count": 1},
    {"name": "沈雾敛", "count": 1},
    {"name": "纯白", "count": 1},
    {"name": "莲琊", "count": 1},
    {"name": "银临", "count": 1},
    {"name": "陈鹏杰", "count": 1},
    {"name": "静雯", "count": 1}
  ],
  "编曲": [
    {"name": "Mzf小慕", "count": 11},
    {"name": "崔博源", "count": 5},
    {"name": "云宏", "count": 4},
    {"name": "1AN孙毅然", "count": 3},
    {"name": "Fsy小诺", "count": 3},
    {"name": "向往", "count": 3},
    {"name": "周果亦", "count": 3},
    {"name": "李大白K", "count": 3},
    {"name": "PoKeR", "count": 2},
    {"name": "何天程", "count": 2},
    {"name": "悠悠酱", "count": 2},
    {"name": "洛劫", "count": 2},
    {"name": "灰原穷", "count": 2},
    {"name": "Terence Teo", "count": 1},
    {"name": "litterzy", "count": 1},
    {"name": "丁嘉昱", "count": 1},
    {"name": "何杰文", "count": 1},
    {"name": "周果亦 新", "count": 1},
    {"name": "安念", "count": 1},
    {"name": "宏宇", "count": 1},
    {"name": "林华瑞", "count": 1},
    {"name": "王景", "count": 1},
    {"name": "蔡成钰", "count": 1}
  ],
  "调校": [
    {"name": "坐标P", "count": 22},
    {"name": "瑞安Ryan", "count": 17},
    {"name": "Creuzer", "count": 10},
    {"name": "花儿不哭", "count": 10},
    {"name": "ShizukaYY", "count": 1},
    {"name": "陌生来访", "count": 1}
  ],
  "演唱": [
    {"name": "赤羽", "count": 23},
    {"name": "星尘（infinity）", "count": 16},
    {"name": "苍穹", "count": 13},
    {"name": "Minus", "count": 10},
    {"name": "海伊", "count": 10},
    {"name": "诗岸", "count": 7},
    {"name": "洛天依", "count": 5},
    {"name": "牧心", "count": 4},
    {"name": "乐正绫", "count": 2},
    {"name": "言和", "count": 2},
    {"name": "KBShinya", "count": 1},
    {"name": "三无Marblue", "count": 1},
    {"name": "乐正龙牙", "count": 1},
    {"name": "九渊", "count": 1},
    {"name": "从铮", "count": 1},
    {"name": "初音未来V4C", "count": 1},
    {"name": "叁琏", "count": 1},
    {"name": "奇然liya", "count": 1},
    {"name": "心华", "count": 1},
    {"name": "赵方婧", "count": 1}
  ]
};
